import { SMCHeader } from "@/components/smc/SMCHeader";
import { trafficAlerts } from "@/data/mockData";
import { AlertTypeBadge } from "@/components/smc/Badges";
import { Bell, MapPin, Clock } from "lucide-react";

export default function SMCAlerts() {
  return (
    <div className="min-h-screen">
      <SMCHeader 
        title="Peak-Hour Traffic Alerts" 
        subtitle="Predictive alerts based on historical data patterns" 
      />
      <div className="p-6 space-y-6">
        {/* Alert Legend */}
        <div className="flex items-center gap-6">
          <div className="flex items-center gap-2">
            <div className="h-4 w-4 rounded bg-warning" />
            <span className="text-sm text-muted-foreground">Watch — Monitor situation</span>
          </div>
          <div className="flex items-center gap-2">
            <div className="h-4 w-4 rounded bg-destructive animate-pulse-slow" />
            <span className="text-sm text-muted-foreground">Act Now — Immediate action required</span>
          </div>
        </div>

        {/* Alerts List */}
        <div className="gov-card">
          <div className="flex items-center justify-between border-b border-border px-5 py-4">
            <div className="flex items-center gap-3">
              <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-destructive/10">
                <Bell className="h-5 w-5 text-destructive" />
              </div>
              <div>
                <h2 className="font-semibold text-foreground">Active & Upcoming Alerts</h2>
                <p className="text-sm text-muted-foreground">Next 2 hours prediction window</p>
              </div>
            </div>
          </div>

          <div className="divide-y divide-border">
            {trafficAlerts.map((alert) => (
              <div key={alert.id} className="flex items-center gap-6 px-5 py-4 hover:bg-muted/30 transition-colors">
                <AlertTypeBadge type={alert.alertType} />
                
                <div className="flex-1">
                  <p className="font-medium text-foreground">{alert.message}</p>
                  <div className="flex items-center gap-4 mt-1">
                    <span className="flex items-center gap-1.5 text-sm text-muted-foreground">
                      <MapPin className="h-3.5 w-3.5" />
                      {alert.location}
                    </span>
                    <span className="flex items-center gap-1.5 text-sm text-muted-foreground">
                      <Clock className="h-3.5 w-3.5" />
                      Expected: {alert.expectedTime}
                    </span>
                  </div>
                </div>

                <button className="btn-gov-secondary text-sm">
                  Acknowledge
                </button>
              </div>
            ))}
          </div>
        </div>

        {/* Prediction Info */}
        <div className="gov-card bg-primary/5 border-primary/20 p-5">
          <h3 className="font-semibold text-foreground mb-2">How predictions work</h3>
          <p className="text-sm text-muted-foreground">
            Alerts are generated by analyzing historical traffic patterns, school/office schedules, 
            market timings, and recurring events. This system does not rely on real-time sensors—it 
            uses pattern recognition from past data to anticipate congestion before it happens.
          </p>
        </div>
      </div>
    </div>
  );
}
